# Generated by Django 4.2.5 on 2023-09-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=800)),
                ('valor', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_prestamos', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Univalluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipoDeUnivalluna', models.CharField(choices=[('E', 'Estudiante'), ('F', 'Funcionario')], max_length=1)),
                ('tipoDeDocumento', models.CharField(choices=[('TI', 'Tarjeta de Idetidad'), ('CC', 'Cedula de Ciudadania')], max_length=2)),
                ('numeroDeDocumento', models.CharField(max_length=50)),
                ('codigoDeEstudiante', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='univalluno',
            constraint=models.UniqueConstraint(fields=('tipoDeDocumento', 'numeroDeDocumento'), name='unico numero de documento por tipo de documento'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='articuloDeportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulodeportivo'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='univalluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.univalluno'),
        ),
        migrations.AddField(
            model_name='multas',
            name='articuloDeportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulodeportivo'),
        ),
        migrations.AddField(
            model_name='multas',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prestamos'),
        ),
        migrations.AddField(
            model_name='multas',
            name='univalluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.univalluno'),
        ),
    ]
