# Generated by Django 4.2.5 on 2023-09-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='multas',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
