# Generated by Django 4.2.5 on 2023-09-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_prestamos_fecha_vencimiento_prestamos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univalluno',
            name='codigoDeEstudiante',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
