# Generated by Django 4.2.5 on 2023-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_univalluno_codigodeestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodeportivo',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
