# Generated by Django 4.2.5 on 2023-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_articulodeportivo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multas',
            name='pagado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='multas',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
