# Generated by Django 4.2.5 on 2023-10-01 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_multas_pagado_alter_multas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multas',
            name='fecha_pago',
            field=models.DateTimeField(null=True),
        ),
    ]
